name: EmApi
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_management 
    ports:
      - 5433:5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
